### PR TITLE
SAMBA submodule for develop branch

### PR DESCRIPTION
**Pull request by asemposki**
Now this should be working---I am adding SAMBA as a submodule to the develop branch of bandframework so that it can be easily accessed.

### CODE REVIEW

**Comment by MattPlumlee** [comment]
Going to be a bit close to the rules while we start out.  You can keep updating your branch/this conversation as we go, you will not need to submit a new pull request.

Some comments:

- Please indicate in the pull request text who tested your package as described in the `README` and tag them as reviewers.  They should write their approval here.
- For your notebook instructions for testing, please include some expected output in addition to looking for "no errors".  This will help verify that the software is working correctly.
- For your warnings, go ahead and include some common warnings (maybe just the ones seen by the testers).

**Comment by asemposki** [comment]
1). Testers for the SAMBA package are Daniel Odell and Ozge Surer. They have now been tagged as reviewers of this PR. Both will have tested SAMBA by next week, so this can be merged once they have approved it. 

2). I have now included some expected array output and estimated values for the methods in the notebooks, so they can be checked against something when tested. I will also add a README there to discuss the process a bit. 

3). I have now included the warnings that pytest has raised when testing using the Tests folder files in the README of that folder.

**Comment by MattPlumlee** [comment]
@odell and @ozgesurer : once you have tested and found success, please post here or let me know and we can merge.

**Review by odell — APPROVED** [review]
## Tutorials

All 3 tutorial notebooks ran flawlessly. Every cell executed without warnings or errors.

I have 1 suggestion: You have saved results in the notebooks. If the user is expected to compare those by eye, maybe it would be easier to summarize the difference between the saved results and the user's output with some kind of metric, e.g. norm of the difference.

## Tests

All tests passed. (I had to install `pytest`, but that's simple enough.)

Several Matplotlib windows popped up with _really_ big plots.  If the user is meant to get something out of those plots, the size needs to be corrected. Here's one as an example:

Figure_1

I did get the warnings that the README... warns against, but nothing that causes failures. Here's my output:

```
========================================= warnings summary =========================================
../../../../Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/seaborn/rcmod.py:4
  /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/seaborn/rcmod.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion

../../../../Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/h5py/__init__.py:36
  /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.12.2 when it was built against 1.12.1, this may cause problems
    _warn(("h5py is running against HDF5 {0} when it was built against {1}, "

../../../../Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/emcee/utils.py:23
../../../../Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/emcee/utils.py:23
  /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/emcee/utils.py:23: DeprecationWarning: 'chain' is deprecated. Use 'get_chain()' instead.
    deprecation_warning(msg)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================ 18 passed, 4 warnings in 259.77s (0:04:19) ============================
```

## Conclusion

Very nice work, Alexandra. 👏

**Review by ozgesurer — APPROVED** [review]
Excellent, Alexandra! I was able to run 3 tutorials, and pass the 15 tests. Moving forward, if you are willing to convert this to a python package, and given that you have setup file, I will just leave a couple sentences here, and feel free to ignore if you don't like. You can run the following 2 example lines in your terminal within SAMBA's directory
                                                  - python3 setup.py sdist bdist_wheel
                                                  - pip install ./dist/SAMBA-0.1.tar.gz 
to see if you can also install SAMBA as a python package. That way, you can get rid of the path problem that you had. If we don't install it as a package, we need to add python paths. But, if you install it as a package, you don't need it. Overall, everything is great!

**Pull request merged**
