### PR TITLE
V04/puq

### PR DESCRIPTION
**Pull request by ozgesurer**
@mosesyhc Thanks for volunteering to review PUQ. If you can follow the steps here https://github.com/parallelUQ/PUQ, to install, test, and replicate one example from the paper, I think it should be good.

@wildsm You already run those examples. I included an sdk document for PUQ under band framework, updated README.md to include PUQ, and the sdkpolicies/README.md to include the link to the PUQ SDK.

### CODE REVIEW

**Comment by ozgesurer** [comment]
About Failing Actions: The link to the SDK is unsuccessful since there is no SDK in the repo yet.

**Comment by wildsm** [comment]
Click through on PUQ sdk link works; should be good post merge

**Review by wildsm — COMMENTED** [review]
Tests pass:

`============================== 3 passed in 9.16s ==============================`

**Review by wildsm — COMMENTED** [review]
Note that running `make html` in `docs/` as instructed in the README does not succeed. 

Perhaps there is missing a `docs/Makefile` @ozgesurer ?

**Comment by wildsm** [comment]
FWIW, I noticed that the libensemble dependency in this version is pre v1.0.0 (and a significant API change). If libensemble is bumped up to the current v1.4.2, the above tests still succeed. See https://github.com/parallelUQ/PUQ/pull/9

I'm not necessarily suggesting that the REQUIREMENTS be updated given that there is currently a tagged version and a subsequent (post bandframework v0.4.0) PUQ release is planned. Instead, it would good for @ozgesurer to check whether bumping up the libensemble version in PUQ messes anything up in the various paper branches.

**Comment by ozgesurer** [comment]
@wildsm @mosesyhc I will also check the docs later today so that Moses can try with the fixed version.

**Comment by mosesyhc** [comment]
I have completed all the tests, and ran the examples as well. All have passed.

Two suggestions for changes:
- At first I had `./run-tests.sh` fail on all tests. After examining and rereading the instructions, I realize I never thought to install `pytest, pytest-cov`.  It might be an overkill, but it may help to include `pip install pytest pytest-cov` right before `./run-tests.sh`.  (I admit I skim and mostly read only the code parts, though.. I may not be the only one.)
- For docs, replacing `cd docs; make html` with `sphinx-build -M html docs docs` will work. You won't need to move into the `docs` directory to build the documentation.  The outputs will still be found under `docs/html`.

**Review by mosesyhc — COMMENTED** [review]
@ozgesurer I have completed all the tests, and ran the examples as well. All have passed.

Two suggestions for changes:
- At first I had `./run-tests.sh` fail on all tests. After examining and rereading the instructions, I realize I never thought to install `pytest, pytest-cov`.  It might be an overkill, but it may help to include `pip install pytest pytest-cov` right before `./run-tests.sh`.  (I admit I skim and mostly read only the code parts, though.. I may not be the only one.)
- For docs, replacing `cd docs; make html` with `sphinx-build -M html docs docs` will work. You won't need to move into the `docs` directory to build the documentation.  The outputs will still be found under `docs/html`.

**Comment by mosesyhc** [comment]
Also, I can verify that PUQ works with libensemble==0.9.1 on a **Python 3.11** machine.

**Comment by ozgesurer** [comment]
Thanks @mosesyhc for the suggestions.

- I updated the instructions for compiling the documentation, so it should work now.  @wildsm Please feel free to check as well.
- I also added Python 3.11 to our dependencies, since we are actually checking it in the actions.

**Comment by ozgesurer** [comment]
@mosesyhc I did not need to install ``pytest`` even though I test it in a new environment. Interesting! But, additional info does not hurt. So, included ``pip install pytest pytest-cov`` under testing. Thanks.

**Review by mosesyhc — APPROVED** [review]

**Pull request merged**
