### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by wildsm**
Opening a pull request for others to take a look at current template for a code of conduct.

Comments welcome.

### CODE REVIEW

**Comment by MattPlumlee** [comment]
I wont merge just yet and wait for comments, but I think it looks good.  Is that email address controlled by you Stefan?

**Comment by wildsm** [comment]
Thanks, let's not merge yet until more stakeholders have had a chance to look.

See [Issue 22](https://github.com/bandframework/bandframework/issues/22#issue-1275576820) regarding mail address. Comments welcome at issue or here.

My convention would be to effectively subscribe folks (Band admins, conduct committee, PI only) to receive emails sent to the address. So far, the email goes to no one.

An alternative could be to set up a github group within the organization and then manage emails through that group. 

For now, I think the priority is to state a code of conduct. If suddenly this group produces lots of software or expands the community significantly, we should revisit.

**Comment by ozgesurer** [comment]
Thanks @wildsm It looks good to me

**Comment by furnstahl** [comment]
This looks good. Thanks.

**Review by furnstahl — APPROVED** [review]

**Review by ozgesurer — APPROVED** [review]

**Comment by DanielRPhillips** [comment]
I like the code of conduct too. You may have saved me a bunch of work, since I think we could, mutatis mutandis, pretty much adopt this as the BAND code of conduct. 

I will post in Slack to alert those not following here that we are working on this.

I'll respond to the mailbox question under the Issue.

**Comment by mpratola** [comment]
Thumbs up for me.

**Review by odell — APPROVED** [review]

**Comment by wildsm** [comment]
Merging now, can always edit, especially before develop moves to main...

**Pull request merged**
