### PR TITLE
V04/surmise

### PR DESCRIPTION
**Pull request by mosesyhc**
For BAND reviewers (@asemposki, @wildsm), first of all, thanks for spending the time to review and test.  Below is a review checklist:

- [ ] **Copy the following in a new comment for your review**.

*Functionality tests*
- [ ] Follow instruction under [Installation](https://surmise.readthedocs.io/en/latest/introduction.html#installation) to install surmise.  If you have an existing surmise installation, you may want to upgrade surmise with `pip install surmise --upgrade`.
- [ ] ```import surmise; print(surmise.__version__)``` should return `0.3.0`.
- [ ] Clone the repository and run the test suite under [Testing](https://surmise.readthedocs.io/en/latest/introduction.html#testing)
  - Warnings `ConvergenceWarning` in testing PCGPwImpute is expected.
- [ ] Run Examples Jupyter notebooks 1 - 4 in `examples/Examples*/` 
  - Warnings about `empirical_coverage` are expected in Example 3.
  - Example 4 can take significantly longer.
- [ ] Run `GP_surmise` Jupyter notebook in `examples/UsageTutorial/`.  This reproduces the [public colab jupyter notebook](https://colab.research.google.com/drive/1f4gKTCLEAGE8r-aMWOoGvY-O6zNqg1qj?usp=drive_link).

*Documentation review:*
- [ ] Review [surmise BAND SDK](https://github.com/bandframework/surmise/blob/v0.3.0/surmisebandsdk.md)

### CODE REVIEW

**Comment by wildsm** [comment]
Note that there is no reason to add words that erred in
https://github.com/bandframework/bandframework/actions/runs/10815835398
to the word list. Those are associated with a file in main for which it's my understanding that will not be included in the next bandframework release.

**Review by wildsm — COMMENTED** [review]
Starting review:

*Functionality tests*
- [x] Follow instruction under [Installation](https://surmise.readthedocs.io/en/latest/introduction.html#installation) to install surmise.  If you have an existing surmise installation, you may want to upgrade surmise with `pip install surmise --upgrade`.

- [x] ```import surmise; print(surmise.__version__)``` should return `0.3.0`.

Note that simply doing `pip install surmise` on my system was insufficient. 
It resulted in 
```
> import surmise; print(surmise.__version__)
0.2.2.dev107+g4680583
```

However, `pip install surmise --upgrade`
succeeded: `0.3.0`

- [x] Clone the repository and run the test suite under [Testing](https://surmise.readthedocs.io/en/latest/introduction.html#testing)

Originally I ran pytest from `../tests/` which resulted in an error (probably because of an issue with expected relative paths?). Following the instructions and running from `tests/` produced:


```
$ python -m pytest 
========================================== test session starts ==========================================
platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/wild/oldcomp/repos/bandframework/software/surmise
configfile: pyproject.toml
plugins: cov-5.0.0, dash-2.17.1, anyio-4.3.0
collected 287 items                                                                                     

test_emu_cal/test_cal_directbayes.py .............                                                [  4%]
test_emu_cal/test_cal_directbayeswoodbury.py ..............                                       [  9%]
test_emu_cal/test_cal_mh.py .....................                                                 [ 16%]
test_emu_cal/test_cal_saveload.py ...                                                             [ 17%]
test_emu_cal/test_emu_init.py ................................................................... [ 41%]
.......                                                                                           [ 43%]
test_emu_cal/test_emu_param_str.py ......                                                         [ 45%]
test_emu_cal/test_emu_passfunc.py ....                                                            [ 47%]
test_emu_cal/test_emu_pcgpwimpute.py .....                                                        [ 48%]
test_emu_cal/test_emu_pcgpwm.py ..............                                                    [ 53%]
test_emu_cal/test_emu_predict.py ...............................                                  [ 64%]
test_emu_cal/test_emu_remove.py ..                                                                [ 65%]
test_emu_cal/test_emu_saveload.py ...                                                             [ 66%]
test_emu_cal/test_emu_supplement.py .................                                             [ 72%]
test_emu_cal/test_emu_update.py ........................                                          [ 80%]
test_emu_cal/test_emu_x1d.py ..                                                                   [ 81%]
test_new_calibrator/test_new_cal.py ........................                                      [ 89%]
test_new_emulator/test_new_emu.py ........................                                        [ 97%]
test_new_emulator/test_new_emu_prediction.py ......                                               [100%]

=========================================== warnings summary ============================================
tests/test_emu_cal/test_emu_pcgpwimpute.py::test_imputemethod[RandomForest-expectation2]
  /home/wild/.local/lib/python3.10/site-packages/sklearn/impute/_iterative.py:801: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================== 287 passed, 1 warning in 187.29s (0:03:07) ===============================
```

The one warning is consistent with:

  - Warnings `ConvergenceWarning` in testing PCGPwImpute is expected.
   
- [x] Run Examples Jupyter notebooks 1 - 4 in `examples/Examples*/` 
  - Warnings about `empirical_coverage` are expected in Example 3.
  - Example 4 can take significantly longer.

Examples 1 & 2 ran without warning. Example 3 produced a few 
```
UserWarning: Use the same 'x' for prediction to compute empirical coverages.
  warnings.warn('Use the same \'x\' for prediction to compute empirical coverages.')
```
As noted in the conversation, I did have to change the 2 lines loading the csv to `ball = np.loadtxt('ball.csv', delimiter=',')`.


In Example 4, I again had to remove the extra path in all the csv np.loadtxt calls.


  
- [ ] Run `GP_surmise` Jupyter notebook in `examples/UsageTutorial/`.  This reproduces the [public colab jupyter notebook](https://colab.research.google.com/drive/1f4gKTCLEAGE8r-aMWOoGvY-O6zNqg1qj?usp=drive_link).

All good. 
Note that on older versions (pre 3.8?) of matplotlib one has to comment out 1 line at the start of the notebook:
```
plt.style.use('seaborn-v0_8-colorblind')
```

*Documentation review:*
- [x] Review [surmise BAND SDK](https://github.com/bandframework/surmise/blob/v0.3.0/surmisebandsdk.md)

As a result of this review, minor changes were made to the bandsdk template (and included in this PR).
Edits were also done on the surmise sdk; see https://github.com/bandframework/surmise/pull/143 . 
The surmise sdk edits do not structurally change the sdk and hence need not be part of this update to the bandframework.

**Comment by mosesyhc** [comment]
@wildsm : Have you run `python -m pytest` from the `tests/` directory? or from the root surmise directory?

**Comment by wildsm** [comment]
> @wildsm : Have you run `python -m pytest` from the `tests/` directory? or from the root surmise directory?

Excellent, I was running it one level up from `tests/`.

**Comment by asemposki** [comment]
Starting my review here. 

- [ ] **Copy the following in a new comment for your review**.

*Functionality tests*
- [ ] Follow instruction under [Installation](https://surmise.readthedocs.io/en/latest/introduction.html#installation) to install surmise.  If you have an existing surmise installation, you may want to upgrade surmise with `pip install surmise --upgrade`.
- [ ] ```import surmise; print(surmise.__version__)``` should return `0.3.0`.
- [ ] Clone the repository and run the test suite under [Testing](https://surmise.readthedocs.io/en/latest/introduction.html#testing)
  - Warnings `ConvergenceWarning` in testing PCGPwImpute is expected.
- [ ] Run Examples Jupyter notebooks 1 - 4 in `examples/Examples*/` 
  - Warnings about `empirical_coverage` are expected in Example 3.
  - Example 4 can take significantly longer.
- [ ] Run `GP_surmise` Jupyter notebook in `examples/UsageTutorial/`.  This reproduces the [public colab jupyter notebook](https://colab.research.google.com/drive/1f4gKTCLEAGE8r-aMWOoGvY-O6zNqg1qj?usp=drive_link).

*Documentation review:*
- [ ] Review [surmise BAND SDK](https://github.com/bandframework/surmise/blob/v0.3.0/surmisebandsdk.md)

**Review by asemposki — APPROVED** [review]

**Comment by wildsm** [comment]
> The SDK should probably be updated from v0.2 to v0.4 at the top in the header, but I could be wrong? I updated `Taweret`'s SDK in this way.

@asemposki - It is version 0.2 of the sdk, so should be 0.2 in Taweret sdk.

**Comment by mosesyhc** [comment]
> When running Notebook 3, the file path for ''ball.csv'' was not working for me, so I simply removed the parent indication and used the file name since it is in the same directory.
> ## Example notebook 4 has the same problem, pasted below:
> 
> NameError Traceback (most recent call last) Cell In[2], line 3 1 # Read data ----> 3 parent_path = Path(**file**).parent 4 real_data = np.loadtxt(parent_path / 'real_observations.csv', delimiter=',') 5 description = np.loadtxt(parent_path / 'observation_description.csv', delimiter=',', dtype='object')
> 
> NameError: name '**file**' is not defined
> 
> I simply removed the parent path again and it worked. I opened the Jupyter Notebook in Jupyter, and opened the Jupyter server in the top directory of surmise, so it could be where I opened the server that might be the problem.
> 

Thanks, @asemposki. Were you running the `.ipynb` notebook files, or the `.py` files? The `ipynb` files do not call `__file__`. I believe the `__file__` call works in a Python environment, but Jupyter notebooks use the IPython environment. I may include additional descriptions for the `.py` files, for those are used when run with `python ExampleX.py`.

> The final calibrator in Example 4 was taking a _very_ long time; I took the number of samples down to 10 but it still took an equally long amount of time. How long is this run approximately supposed to take?

The final calibrator relies on the `directbayeswoodbury`, which I think causes the difference.  Previously it ran for around half an hour.

**Comment by asemposki** [comment]
@mosesyhc I was running the .ipynb files.

**Comment by asemposki** [comment]
@mosesyhc I found it! I was indeed using v0.3.0 as I thought, considering I cloned the repo this morning. :) BUT I was using Jupyter Lab, and somehow it was including that call, but when I used a different virtual environment with an older version of Jupyter notebook, it doesn't have that call and indeed looks like the GitHub preview when you pull up the notebooks. I did not realise Lab would do that, it's very odd.

**Comment by mosesyhc** [comment]
> @mosesyhc I found it! I was indeed using v0.3.0 as I thought, considering I cloned the repo this morning. :) BUT I was using Jupyter Lab, and somehow it was including that call, but when I used a different virtual environment with an older version of Jupyter notebook, it doesn't have that call and indeed looks like the GitHub preview when you pull up the notebooks. I did not realise Lab would do that, it's very odd.

Thanks for the detective work!  That is an interesting find, though that is still very odd ...

**Review by wildsm — COMMENTED** [review]
Any idea why I am getting these warnings in Examples 3 and 4?
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[4], line 2
      1 # Read the data
----> 2 ball_filepath = Path(__file__).parent / "ball.csv"
      3 ball = np.loadtxt(ball_filepath, delimiter=',')
      4 m = len(ball)

NameError: name '__file__' is not defined
```

**Comment by mosesyhc** [comment]
> Any idea why I am getting these warnings in Examples 3 and 4?
> 
> ```
> ---------------------------------------------------------------------------
> NameError                                 Traceback (most recent call last)
> Cell In[4], line 2
>       1 # Read the data
> ----> 2 ball_filepath = Path(__file__).parent / "ball.csv"
>       3 ball = np.loadtxt(ball_filepath, delimiter=',')
>       4 m = len(ball)
> 
> NameError: name '__file__' is not defined
> ```
> 
> (I am running Example3_nb.ipynb in jupyter-notebook, so maybe different the issue noted above?)

Unsure why that line exists in `Example3_nb.ipynb`... this is what the lines look like to me:
```
# Read the data
ball = np.loadtxt('ball.csv', delimiter=',')
m = len(ball)
```
referring to the file in question: https://github.com/bandframework/surmise/blob/v0.3.0/examples/Example3/Example3_nb.ipynb

**Comment by asemposki** [comment]
Yes, that is the same issue I reported. Good that we found out why. I have not had the time to revisit it today.

**Comment by wildsm** [comment]
> @wildsm : I think I understand now.. the `.py` file has configuration details at the beginning, specifying `jupyter`. (referring to https://github.com/bandframework/surmise/blob/v0.3.0/examples/Example3/Example3_nb.py). We may have to remove these specifications in the `.py` files and hopefully Jupyter does not get confused. At the end of the day, I think we probably want to keep only one set of examples, instead of both `.py` and `.ipynb`.

Yes, that worked (see my review). Agreed that only one of .py and .pynb should be maintained.

**Review by wildsm — APPROVED** [review]
Review complete, see notes in this thread and my edited checklist.

**Comment by mosesyhc** [comment]
Thank you both, @asemposki and @wildsm. The changes to examples are implemented in [surmise/216a126](https://github.com/bandframework/surmise/pull/145/commits/216a126702ed83c32bdb7d77c2f9c34b6f9a84b0). 

Since these are relatively minor changes, I am inclined to hold these changes until a minor update and pull them in.  And the current surmise v0.3.0 will stay as is for BAND v0.4.  Would this be acceptable to you?

**Comment by wildsm** [comment]
yes for me. Add issues to surmise to address in next mini release.

**Comment by mosesyhc** [comment]
I am including these fixes in [surmise/#146](https://github.com/bandframework/surmise/issues/146).

With this comment, I will merge and close the PR.

**Pull request merged**
