### PR TITLE
Add jitr as BAND software for v04

### PR DESCRIPTION
**Pull request by beykyle**
- Adds [github.com/beykyle/jitr](https://github.com/beykyle/jitr) as a git submodule in software

### CODE REVIEW

**Comment by wildsm** [comment]
@beykyle - can you please change the target branch to `develop` (instead of `main`)?

**Comment by beykyle** [comment]
@wildsm done!

**Comment by wildsm** [comment]
Following the instructions at
https://github.com/beykyle/jitr/tree/37c313dc7dea7abc024516117c43d00f48ed22d1

1.  `pip install jitr` succeeds
2.  `pytest` from the main directory fails with the following output:


```
=========================== short test summary info ============================
FAILED test/test_coupled_single_dwba.py::test_coupled_vs_single - TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'dtype'
FAILED test/test_local.py::test_local - TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'dtype'
FAILED test/test_wavefunction.py::test_wavefunction - TypeError: _vhstack_dispatcher() got an unexpected keyword argument 'dtype'
=================== 3 failed, 2 passed, 6 warnings in 6.87s ====================
```

The warnings relate to `utils.py`: 

```
DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
```

Is anyone else able to reproduce?
@beykyle any thoughts on a fix?

**Review by wildsm — COMMENTED** [review]
Checking the `jitrbandsdk.md`

1. The first two `here` links should be updated so that do not point to a relative location (which does not exist); see correct links, e.g., at https://github.com/bandframework/surmise/blob/main/surmisebandsdk.md .
2. M1: I did not see the `setup.py` that was mentioned.
3. M3: The `the jitr team` link was broken for me. (This could be associated with the particular commit for the PR/submodule? E.g., M7 `requirements.txt` is also broken for me).
4. R3: Consider linking to `requirements.txt` for consistency with M7.
5. R6: For me, the `examples/` link lands at https://github.com/beykyle/bandframework/blob/main/examples/README.md instead of what was actually desired.
6. R14: `test\` link broken for me, but may be related to M3 above.

**Comment by wildsm** [comment]
Will add manuelcatacora

Kyle is this ready or still a draft?

**Comment by beykyle** [comment]
Hey @wildsm, thank you for reviewing. I will look into these today and report back.

**Comment by beykyle** [comment]
@wildsm I believe all the links should be fixed, and and the test that wasn't working on your machine *should* work, as of https://github.com/beykyle/jitr/releases/tag/v1.4. I will update this PR to point to the correct jitr version.

**Comment by beykyle** [comment]
@wildsm  Done, looks like no more merge conflicts here.

**Comment by wildsm** [comment]
@beykyle - check out https://github.com/beykyle/bandframework/pull/1

**Comment by wildsm** [comment]
Some quick comments from me on the latest version:

1. Under the testing header of https://github.com/beykyle/jitr/tree/f8f323e7101aed2baa5ffb2ebf837f7a66fb6ea0 , I believe that you should specify that you are need to run from the `testing/` directory.
2. When I run pytest as directed (i.e., after a pip install and in the branch of jitr corresponding to the current submodule), I obtain the following output (1 error, rest warnings associated with deprecation):

```
========================================== test session starts ==========================================
platform linux -- Python 3.10.12, pytest-7.4.2, pluggy-1.2.0
rootdir: /home/wild/oldcomp/repos/testing/bandframework/software/jitr/test
plugins: cov-5.0.0, dash-2.17.1, anyio-4.3.0
collected 5 items                                                                                       

test_coupled_single_dwba.py .                                                                     [ 20%]
test_integration.py ..                                                                            [ 60%]
test_local.py .                                                                                   [ 80%]
test_wavefunction.py F                                                                            [100%]

=============================================== FAILURES ================================================
___________________________________________ test_wavefunction ___________________________________________

    def test_wavefunction():
        E = 14.1
        nodes_within_radius = 5
    
        # target (A,Z)
        Ca48 = (28, 20)
        mass_Ca48 = 44657.26581995028  # MeV/c^2
    
        # projectile (A,z)
        proton = (1, 1)
        mass_proton = 938.271653086152  # MeV/c^2
    
        sys = ProjectileTargetSystem(
            channel_radii=np.array([nodes_within_radius * (2 * np.pi)]),
            l=np.array([1]),
            mass_target=mass_Ca48,
            mass_projectile=mass_proton,
            Ztarget=Ca48[1],
            Zproj=proton[1],
        )
    
        # Woods-Saxon potential parameters
        V0 = 70  # real potential strength
        W0 = 40  # imag potential strength
        R0 = 6  # Woods-Saxon potential radius
        a0 = 1.2  # Woods-Saxon potential diffuseness
        params = (V0, W0, R0, a0, sys.Zproj * sys.Ztarget, R0)
    
        ints = InteractionMatrix(1)
        ints.set_local_interaction(interaction, args=params)
    
        channels = sys.build_channels_kinematics(E)
        channel_data = make_channel_data(channels)
        s_values = np.linspace(0.01, sys.channel_radii[0], 200)
    
        # Lagrange-Mesh
        solver_lm = RMatrixSolver(100)
        R_lm, S_lm, x, uext_prime_boundary = solver_lm.solve(
            ints, channels, wavefunction=True
        )
        u_lm = Wavefunctions(
            solver_lm, x, S_lm, uext_prime_boundary, sys.incoming_weights, channel_data
        ).uint()[0]
        u_lm = u_lm(s_values)
    
        # Runge-Kutta
        ch = channel_data[0]
        domain, init_con = ch.initial_conditions()
        sol_rk = solve_ivp(
            lambda s, y: schrodinger_eqn_ivp_order1(
                s, y, ch, ints.local_matrix[0, 0], params
            ),
            domain,
            init_con,
            dense_output=True,
            atol=1.0e-12,
            rtol=1.0e-12,
        ).sol
        a = domain[1]
        u_rk = sol_rk(s_values)[0]
        R_rk = sol_rk(a)[0] / (a * sol_rk(a)[1])
        S_rk = smatrix(R_rk, a, ch.l, ch.eta)
    
        np.testing.assert_almost_equal(R_rk, R_lm[0, 0], decimal=5)
        np.testing.assert_almost_equal(S_rk, S_lm[0, 0], decimal=5)
    
        ratio = u_lm[40] / u_rk[40]
        u_rk *= ratio
>       np.testing.assert_allclose(
            np.absolute(u_rk - u_lm) / (np.absolute(u_rk)), 0, atol=1e-3
        )

test_wavefunction.py:92: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<function assert_allclose.<locals>.compare at 0x7dca99a59120>, array([1.21844811e-01, 3.04066447e-03, 4.31280430e-04,...-07, 1.50478670e-07, 1.70989306e-07,
       1.90852389e-07, 2.04136029e-07, 2.16684882e-07, 2.28590198e-07]), array(0))
kwds = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-07, atol=0.001', 'verbose': True}

    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=0.001
E           
E           Mismatched elements: 2 / 200 (1%)
E           Max absolute difference: 0.12184481
E           Max relative difference: inf
E            x: array([1.218448e-01, 3.040664e-03, 4.312804e-04, 5.899223e-04,
E                  2.881603e-04, 1.720283e-04, 1.307541e-04, 1.179609e-04,
E                  8.215593e-05, 3.913352e-05, 1.295961e-05, 3.155845e-05,...
E            y: array(0)

/usr/lib/python3.10/contextlib.py:79: AssertionError
=========================================== warnings summary ============================================
../../../../../../../.local/lib/python3.10/site-packages/jitr/utils.py:142: 2 warnings
test_local.py: 20 warnings
test_wavefunction.py: 2 warnings
  /home/wild/.local/lib/python3.10/site-packages/jitr/utils.py:142: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
    return derivative(lambda z: H_plus(z, l, eta, asym), s, dx=dx)

../../../../../../../.local/lib/python3.10/site-packages/jitr/utils.py:149: 2 warnings
test_local.py: 20 warnings
test_wavefunction.py: 2 warnings
  /home/wild/.local/lib/python3.10/site-packages/jitr/utils.py:149: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
    return derivative(lambda z: H_minus(z, l, eta, asym), s, dx=dx)

test_coupled_single_dwba.py::test_coupled_vs_single
  /home/wild/.local/lib/python3.10/site-packages/jitr/rmatrix.py:46: NumbaPerformanceWarning: '@' is faster on contiguous arrays, called on (Array(complex128, 1, 'C', False, aligned=True), Array(complex128, 2, 'A', False, aligned=True))
    R, Ainv = rmatrix_with_inverse(A, b, nchannels, nbasis, a)

test_local.py: 10 warnings
  /home/wild/oldcomp/repos/testing/bandframework/software/jitr/test/test_local.py:121: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    error_matrix[l, i] = err

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================== short test summary info ========================================
FAILED test_wavefunction.py::test_wavefunction - AssertionError: 
=============================== 1 failed, 4 passed, 59 warnings in 18.75s ===============================
```

**Comment by beykyle** [comment]
@wildsm Thanks for testing, let me take a look.

**Comment by beykyle** [comment]
Hey @wildsm, I am unable to reproduce this failed test. Can you send me the versions of `scipy` and `numpy` you are using?

I am close to another release, I can try updating to point toward that and see if that fixes things on your end.

**Comment by beykyle** [comment]
I will keep looking into the test that failed. As far as the warnings, there is an open issue that addresses the ones related to `scipy.derivative`. I'll make issues for the other two.

**Comment by wildsm** [comment]
I resolved the merge conflict. @beykyle are you sticking with this version or did you want to use the newer release mentioned above?

**Comment by wildsm** [comment]
@beykyle - please add `pandas` to the requirements

**Comment by beykyle** [comment]
@wildsm done

**Comment by wildsm** [comment]
After installing `pandas-2.2.3`, the tests succeed with the following known warnings:
```
================================ test session starts ================================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/wild/oldcomp/repos/test2/jitr
configfile: pyproject.toml
collected 5 items                                                                   

test/test_coupled_single_dwba.py .                                            [ 20%]
test/test_integration.py ..                                                   [ 60%]
test/test_local.py .                                                          [ 80%]
test/test_wavefunction.py .                                                   [100%]

================================= warnings summary ==================================
src/jitr/utils/free_solutions.py:92: 33 warnings
test/test_local.py: 60 warnings
test/test_wavefunction.py: 1 warning
  /home/wild/oldcomp/repos/test2/jitr/src/jitr/utils/free_solutions.py:92: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
    return derivative(lambda z: H_plus(z, l, eta, asym), s, dx=dx)

src/jitr/utils/free_solutions.py:99: 33 warnings
test/test_local.py: 60 warnings
test/test_wavefunction.py: 1 warning
  /home/wild/oldcomp/repos/test2/jitr/src/jitr/utils/free_solutions.py:99: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
    return derivative(lambda z: H_minus(z, l, eta, asym), s, dx=dx)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 5 passed, 188 warnings in 22.27s =========================
```

I.e., all good once pandas dependencies addressed

**Review by wildsm — APPROVED** [review]
After installing `pandas-2.2.3`, the tests succeed with the following known warnings:
```
================================ test session starts ================================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/wild/oldcomp/repos/test2/jitr
configfile: pyproject.toml
collected 5 items                                                                   

test/test_coupled_single_dwba.py .                                            [ 20%]
test/test_integration.py ..                                                   [ 60%]
test/test_local.py .                                                          [ 80%]
test/test_wavefunction.py .                                                   [100%]

================================= warnings summary ==================================
src/jitr/utils/free_solutions.py:92: 33 warnings
test/test_local.py: 60 warnings
test/test_wavefunction.py: 1 warning
  /home/wild/oldcomp/repos/test2/jitr/src/jitr/utils/free_solutions.py:92: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
    return derivative(lambda z: H_plus(z, l, eta, asym), s, dx=dx)

src/jitr/utils/free_solutions.py:99: 33 warnings
test/test_local.py: 60 warnings
test/test_wavefunction.py: 1 warning
  /home/wild/oldcomp/repos/test2/jitr/src/jitr/utils/free_solutions.py:99: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
    return derivative(lambda z: H_minus(z, l, eta, asym), s, dx=dx)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 5 passed, 188 warnings in 22.27s =========================
```

I.e., all good now that pandas dependencies addressed

**Comment by wildsm** [comment]
Thanks @beykyle

**Comment by beykyle** [comment]
Thanks for the help on this @wildsm !

**Pull request merged**
