### PR TITLE
Pulling in Samba & Taweret (Test)

### PR DESCRIPTION
**Pull request by wildsm**

### CODE REVIEW

**Comment by wildsm** [comment]
A possible fix for #76 .
This PR can be deleted if that one is merged in.

**Comment by wildsm** [comment]
For reference #76 contains the dialog that and reviews that led to this PR

**Review by asemposki — APPROVED** [review]
Looks good, all of the commits are up to date.

**Comment by wildsm** [comment]
Thanks @mosesyhc @jcyannotty @ozgesurer

**Comment by asemposki** [comment]
Thanks everyone!

**Pull request merged**
