### PR TITLE
Delete resources/workshops/Data2024 directory

### PR DESCRIPTION
**Pull request by wildsm**
This file was added to the bandframework repo (to main nonetheless) but was intended for https://github.com/bandframework/bandframework.github.io

Adding it also resulted in additional spellcheck issues

@DanielRPhillips - please confirm deletion (and that nothing else depends on this URL) by reviewing

@furnstahl - by reviewing can you please help Daniel ensure content shows up in bandframework.github.io?

### CODE REVIEW

**Comment by DanielRPhillips** [comment]
This cannot be deleted until an alternate solution is constructed on bandframework.github.io as this location is the site for information about the forthcoming workshop.

**Comment by wildsm** [comment]
(Also now on main of website repo: https://github.com/bandframework/bandframework.github.io/blob/main/_pages/Data2024Workshop.md
)

**Comment by DanielRPhillips** [comment]
Looks good. Thanks for doing this.

**Review by DanielRPhillips — COMMENTED** [review]
Looks good.

**Review by DanielRPhillips — APPROVED** [review]

**Pull request merged**
