### PR TITLE
Merge ROSE for v0.3

### PR DESCRIPTION
**Pull request by kylegodbey**
ROSE just hit v1.0.0 and is ready for primetime. All builds and docs are automatically deployed in the rose repository and can be found in the repo sidebar. The two tutorials step through the full ROSE life cycle and highlight the core features and use cases of the package.

### CODE REVIEW

**Comment by wildsm** [comment]
Install with pip install succeeded. Running pytests in tests succeeded. Will run through sdk later today

**Review by wildsm — APPROVED** [review]
Added https://github.com/bandframework/rose/pull/47 with some suggested changes to sdk.

**Comment by asemposki** [comment]
At the moment, my system cannot find ROSE despite having pip installed it correctly, so the pytests fail for me. This is most likely an ever-present issue with my Windows OS. I will attempt to fix it.

**Comment by kylegodbey** [comment]
> At the moment, my system cannot find ROSE despite having pip installed it correctly, so the pytests fail for me. This is most likely an ever-present issue with my Windows OS. I will attempt to fix it.

Consider running in codespaces, since it provides a linux environment. It's nice to test on Windows, but I don't want to instigate a dependency-induced breakdown

**Comment by asemposki** [comment]
Yep, doing that now. I did run the tutorial in Colab and that worked just fine. I'll run the pytests here in codespaces.

**Review by asemposki — APPROVED** [review]
Everything looks good! The pytests run and the tutorial notebooks ran in Codespaces. Pip install also works fine.

**Comment by wildsm** [comment]
I'm going to go ahead and merge this in so as to make other changes. Please feel free to reopen if other issues arise.
Congrats rose team

**Pull request merged**
