### PR TITLE
Proposing BMEX for v0.3

### PR DESCRIPTION
**Pull request by kylegodbey**
PR for the inclusion of the Bayesian Mass Explorer into v0.3 of the BAND framework. BMEX has hit a stable release of the core application and is at a good jumping off point for future inclusion of BAND tools. Most testing will happen in the web interface at https://bmex.dev

### CODE REVIEW

**Comment by wildsm** [comment]
Consider aligning the sdk "Description" and the README (currently `BMEX Masses is a web app under the Bayesian Mass Explorer project designed to display binding energies and accompanying mass filters across experimental data and theoretical model predictions.`)

**Comment by wildsm** [comment]
See also #80

**Comment by mosesyhc** [comment]
I referred to [Using BMEX](https://github.com/bandframework/bandframework/tree/v03/bmex/software/BMEX#using-bmex) and tested the described different graphing / reporting features (for certain A/N/Z combinations.  The graph and numerical reports succeeded.  Exporting as pdf also succeeded.

Several observations:
- Share View (Copy link) did not return a link to the current view for me.
- Author format in the bibtex entry is inconsistent. (That said I don't think it changes how biblatex reads this entry.)

To me, once the above is resolved, it is good for inclusion.  The remaining is some other observations when I click around.

Other observations not referred to in the README:
- The Submit Issues icon reaches `github.com refused to connect.` if directly clicked.  But the icon reaches the new issues page if opened with a new tab.
- In selecting a new quantity in graph plotting, I believe there is no indication or graph update for missing data. 
  - e.g., if I have first selected `1D Chains, Isotonic EXP Diff, Binding Energy, N=24, ME2`, and then select `Dataset = AME2020`, no change is observed while the previous graph is still up.

**Comment by wildsm** [comment]
#85 is getting spellcheck in order for BMEX addition

**Comment by kylegodbey** [comment]
Alright, I think all is good on the webapp @mosesyhc if you'd like to check again. The bug where things aren't updating is likely because the difference of experimental data with exp data was ill-defined. We've been encountering lots of these edge cases so thanks for digging it up! It's not fixed yet, but the other issues have been resolved.

I think I addressed your initial comments @wildsm, though I'm unsure of what I should do about the actions that are failing. Nothing jumps out as being spelled *wrong*, but I think you're still holding off on updating the wordlist?

**Review by wildsm — APPROVED** [review]
Tests are passing, looks good!

**Pull request merged**
