### PR TITLE
Updating Taweret for v0.4

### PR DESCRIPTION
**Pull request by asemposki**
We update the `Taweret` submodule in `bandframework/develop` for the v0.4 release of the BAND framework. We include updates to the package's workflows and tests, as well as information for developers in the Read the Docs documentation suite, and a Jupyter Book that contains pedagogical information for new users and the tutorial notebooks previously kept in the documentation suite. 

When reviewing Taweret, please use the checklist below. We desire a reviewer with Linux capabilities using `open-mpi` to test the Taweret package. 

**Note**: if you're a Mac user, the arm64 wheel for MacOS for one of our dependences (OpenBT, the C++ package) currently does not work. We have extensively checked that this package can be built manually on MacOS within the Taweret team, and we have instructions on how to do so in our readme. We will improve this functionality in a release after v0.4 of the BAND framework. 

Functionality tests:
- [ ] Install the Taweret pypi package by downloading from https://pypi.org/project/Taweret/. Open a Python terminal and type `import Taweret`, followed by `print(Taweret.__version__)` and you should see `v1.1.0` pop up.
- [ ] Test the package using `Taweret.test()`. All tests should pass.

User interaction tests:
- [ ] Download the GitHub package from our [page](https://github.com/bandframework/Taweret), so you can access the notebooks contained in the `book` folder.
- [ ] Run one of the Jupyter notebooks found in the folder `Taweret/book/notebooks/LMM`. This may take a few hundred seconds depending on which one is chosen, due to the MCMC sampling call. This will test if `seaborn` and `ptemcee` are properly able to be installed, as they are no longer named directly as Taweret dependences.
- [ ] Go to the Jupyter Book [here](https://bandframework.github.io/Taweret/notebooks/Biv_BMM/Bivariate_Test.html) and test launching to Google Colab using the little rocket shaped button at the top of the notebook page, and see if this notebook will run there. **Note**: you'll need to install Taweret in Colab's server so make sure to uncomment the `! pip install Taweret` line in the first cell of the notebook.

Documentation review:
- [ ] Go to the Jupyter Book [here](https://bandframework.github.io/Taweret) and flip through it to make sure that the Latex and the admonitions are rendering. 

SDK review:
- [ ] Review the Taweret SDK information [here](https://github.com/bandframework/Taweret/blob/main/Taweretbandsdk.md).

### CODE REVIEW

**Review by wildsm — COMMENTED** [review]
Starting review.

I will be attempting to represent:

> We desire a reviewer with Linux capabilities using `open-mpi` to test the Taweret package. 



Functionality tests:
- [x] Install the Taweret pypi package by downloading from https://pypi.org/project/Taweret/. Open a Python terminal and type `import Taweret`, followed by `print(Taweret.__version__)` and you should see `v1.1.0` pop up.
- [x] Test the package using `Taweret.test()`. All tests should pass.

> I obtained the following output
```
================================ test session starts ================================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/wild/oldcomp/repos/test2
collected 13 items                                                                  

venv/lib/python3.10/site-packages/Taweret/tests/test_bivariate_linear.py ...  [ 23%]
venv/lib/python3.10/site-packages/Taweret/tests/test_gaussian.py .....        [ 61%]
venv/lib/python3.10/site-packages/Taweret/tests/test_trees.py .....           [100%]

=========================== 13 passed in 62.35s (0:01:02) ===========================
True
```

User interaction tests:
- [x] Download the GitHub package from our [page](https://github.com/bandframework/Taweret), so you can access the notebooks contained in the `book` folder.
- [x] Run one of the Jupyter notebooks found in the folder `Taweret/book/notebooks/LMM`. This may take a few hundred seconds depending on which one is chosen, due to the MCMC sampling call. This will test if `seaborn` and `ptemcee` are properly able to be installed, as they are no longer named directly as Taweret dependencies.

The following is WIP and can be ignored for now.

1. I started by running `Linear_BMM_with_cdf_function_for_coleman_models`.

This succeeds and makes all plots, but note that in training there are some nans:
```
19:50 bilby INFO    : Finished sampling
19:50 bilby INFO    : Writing checkpoint and diagnostics
19:50 bilby INFO    : Finished writing checkpoint
19:50 bilby INFO    : Run interrupted by signal 15: checkpoint and exit on 77
19:50 bilby INFO    : Run interrupted by signal 15: checkpoint and exit on 77
19:50 bilby INFO    : Sampling time: 0:01:01.550638
19:50 bilby INFO    : Summary of results:
nsamples: 2350
ln_noise_evidence:    nan
ln_evidence: -9.499 +/-  3.108
ln_bayes_factor:    nan +/-  3.108
```


2. I next ran `Linear_BMM_with_step_function_for_SAMBA_models`.

This also had no problems (but similar nans as above). Note that the training had this output line:
```20:04 bilby INFO    : Walkers plot failed with exception cannot unpack non-iterable Axes object```
and thus the plot was empty (but the subsequent `result.plot_corner()` produced the desired histogram).

The final plot looks like 
image


3. I next ran `coleman_models_BMM_comparative_study`.

This also had similar nans as above. 

In the cell right after the nans, the following warning was produced:
```
/tmp/ipykernel_123636/3955572814.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['model'] = label
/tmp/ipykernel_123636/3955572814.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['model'] = label
/tmp/ipykernel_123636/3955572814.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['model'] = label
```

Everything succeeded with the final cell having a marker warning
```
/tmp/ipykernel_123636/1972745161.py:26: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "." (-> marker='.'). The keyword argument will take precedence.
  ax2.errorbar(g,exp_data[0],yerr=exp_data[1], marker='x', label='experimental data', color='red', fmt='.')
```
and producing the image
image


4. I concluded by running `Linear_BMM_with_switchcos_function_for_SAMBA_models_Bilby_constrained_prior`.

This also had no problems (but similar nans as above).
Final plot:
image

**Overall:**

- I do not think these nans present a problem for illustrating the core functionality.
- If the notebooks will be used by many, I suggest running a spell checker through them. 



- [x] Go to the Jupyter Book [here](https://bandframework.github.io/Taweret/notebooks/Biv_BMM/Bivariate_Test.html) and test launching to Google Colab using the little rocket shaped button at the top of the notebook page, and see if this notebook will run there. **Note**: you'll need to install Taweret in Colab's server so make sure to uncomment the `! pip install Taweret` line in the first cell of the notebook.

I first reran this notebook to confirm I was getting something like the figure at the above link.

I then went to collab, uncommented the `! pip install Taweret` line and everything succeeded in the same manner as found locally.

Documentation review:
- [x] Go to the Jupyter Book [here](https://bandframework.github.io/Taweret) and flip through it to make sure that the Latex and the admonitions are rendering. 

The LaTeX rendered beautifully. Note that the way that section 4 is set up, some of the metadata (author and date) is being turned into subsub(sub)section headers. An example is https://bandframework.github.io/Taweret/notebooks/Trees_BMM/Trees_BMM_2D.html

SDK review:
- [ ] Review the Taweret SDK information [here](https://github.com/bandframework/Taweret/blob/main/Taweretbandsdk.md).

This looks fine. For the next version, put a period after the statement of M4.

**Comment by asemposki** [comment]
The nan's are from the code that Dan originally wrote, which I have not had enough time or experience with to work through more carefully and see if they need to be fixed. Hence for now I've left that all alone, though eventually they should be checked more rigorously. I remember Dan's notebooks were getting the same results when he was still in the project. I can flag that for an Issue in Taweret so that we can address that post-release.

The results from the Linear_BMM_with_step_function_for_SAMBA_models notebook I don't remember seeing, so I will run back through and see what happens for me.

**Review by wildsm — APPROVED** [review]
I have completed my review in the check list above. 

Hopefully the comments are helpful for future updates to the package.

From my perspective, this PR can be merged, but I will wait for @asemposki to do so in case additional reviewers are desired, I messed anything up with the two files I edited as part of this PR, or changes are made in light of the comments.

**Comment by asemposki** [comment]
Thanks for the review, @wildsm! Those warnings do indeed appear in our local runs, so I will construct an Issue for Taweret for future cleanup with all of the warnings and checks to do there for when we have some extra time to work on those notebooks. I am happy with the review and will now merge.

**Pull request merged**
