### PR TITLE
Pull request to update surmise submodule in bandframework

### PR DESCRIPTION
**Pull request by mosesyhc**
surmise v0.2.1 is the current release to be included under bandframework software.

Guide for reviewers:
1. (Colab environment) Run the [colab notebook](https://colab.research.google.com/drive/1f4gKTCLEAGE8r-aMWOoGvY-O6zNqg1qj?usp=drive_link).
2. (Local) Follow installation and testing sections under https://surmise.readthedocs.io/en/latest/introduction.html#installation.

### CODE REVIEW

**Comment by wildsm** [comment]
I've confirmed that this goes to v0.2.1 surmise on my machine and in the github html tree

@mosesyhc do you think additional reviews are necessary or has John completed tests?

**Comment by mosesyhc** [comment]
@wildsm: John has indeed completed the tests and the suggested changes went into bandframework/surmise#90.

I will add and leave a reviewer guidance in the first comment above so anyone who wants to look at it has the instructions.  But otherwise, it has gone through its necessary review.

**Review by wildsm — APPROVED** [review]
This all looks good to me.

**Review by jcyannotty — APPROVED** [review]
I ran the tests one more time to double check everything just in case something changed from our round of testing last week. Everything still works on my end!

**Pull request merged**
