### PR TITLE
Documentation associated with the v0.4 release

### PR DESCRIPTION
**Pull request by wildsm**

### CODE REVIEW

**Comment by ozgesurer** [comment]
@wildsm Hoping that I'm in the correct PR...

I'm reviewing the documentation and noticed that the links to [QGP_Bayes] and [nsat] in the README are not working. Would it be better to link directly to their repositories? If so, I can do it.

**Comment by wildsm** [comment]
> @wildsm Hoping that I'm in the correct PR...
> 
> I'm reviewing the documentation and noticed that the links to [QGP_Bayes] and [nsat] in the README are not working. Would it be better to link directly to their repositories? If so, I can do it.

Please do

**Comment by ozgesurer** [comment]
This is a minor issue.

All SDKs listed [here](https://github.com/bandframework/bandframework/tree/v04/documentation/resources/sdkpolicies) have the title 'BAND SDK v0.2' except for SAMBA, which says 'BAND SDK v0.4'. My understanding is that we use BAND SDK v0.2 for BAND Framework v0.4. If that's correct, @asemposki needs to update the title. Otherwise, we'll need to update all the other titles—except Alexandra's! :)

**Comment by asemposki** [comment]
Thanks @ozgesurer for pointing that out; I will fix that submodule.

**Comment by wildsm** [comment]
> Thanks @ozgesurer for pointing that out; I will fix that submodule.

If I click through the current develop
https://github.com/bandframework/bandframework/tree/develop/software
I see the SAMBA sdk as v02, so the previous submodule was OK with this.

On the other hand
https://github.com/bandframework/bandframework/tree/develop/resources/sdkpolicies/README.md
links to 
https://github.com/asemposki/SAMBA/blob/main/SAMBAbandsdk.md
in order to capture any updates that the packages have made to their SDKs.

With @asemposki's recent change to SAMBA's `main` the above link also shows v0.2.

Thanks both.

**Comment by wildsm** [comment]
With authors complete, this is ready for review. 

After approval and merge, we will not yet delete the branch so that subsequent changes can employ it until the release

**Review by ozgesurer — APPROVED** [review]

**Pull request merged**
