### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DanielRPhillips**
Include two participants and remote participation option

### CODE REVIEW

**Review by furnstahl — APPROVED** [review]
Looks fine.

**Comment by wildsm** [comment]
No, please see #104

**Comment by DanielRPhillips** [comment]
@wildsm: the attendees of the workshop need to be updated. Happy to that on bandframework.github.io once a soluton for hosting this content there has been constructed.

As for spellcheck failiure, that is because github does not like airport abbreviations, National Labs, or foreign names. List of spell check fails is:

CMH
BNL
Godbey
LANL
Mumpower
Nazarewicz
Notre
ORNL
OSU
Potel
Pratola
Sobes
Witek
LANL
Neudecker

**Comment by wildsm** [comment]
Closing this PR based on #104

**Pull request closed without merging**
