### PR TITLE
Feature/cleaner dev guide

### PR DESCRIPTION
**Pull request by wildsm**
Draft PR to clean up some of the dev guide and address resource/documentation issues

### CODE REVIEW

**Comment by wildsm** [comment]
Can someone take a look and make sure I didn't mess up typos/links/etc.?
Maybe @mpratola @DanielRPhillips @mosesyhc  or others?

I usually click on "Files changed" toward the top of this pull request, view the changes, and then click the green "Review changes box"

**Review by mosesyhc — APPROVED** [review]
Updated some `develop` branch name references in a new commit.

Reviewed changes and found no other issues.

**Review by wildsm — COMMENTED** [review]
Commit looks great, thanks @mosesyhc !

**Comment by mosesyhc** [comment]
SDK policy to include citation of BAND Framework ? See #62

**Comment by wildsm** [comment]
Made draft to first resolve #62 discussion

**Comment by wildsm** [comment]
@mosesyhc - I think we're good to go now. Do you agree? Will you push the merge button

**Pull request merged**
