### PR TITLE
Release v0.2.0

### PR DESCRIPTION
**Pull request by wildsm**

### CODE REVIEW

**Comment by wildsm** [comment]
Related to https://github.com/bandframework/bandframework/issues/46

**Review by wildsm — COMMENTED** [review]
Deleted some extraneous files and updated BAND SDK version in Bfrescox tutorial

**Review by danOSU — APPROVED** [review]
There are some files that belong to certain application that I do not have the domain knowledge  to review. I did not check the viewed box for them. Everything else looks good.

**Review by odell — APPROVED** [review]

**Review by ozgesurer — APPROVED** [review]
Well done to us!

**Pull request merged**
