### PR TITLE
updating SAMBA + Taweret

### PR DESCRIPTION
**Pull request by asemposki**
This PR should cover merging SAMBA's newest commit as the pointer for the submodule.

### CODE REVIEW

**Comment by asemposki** [comment]
OK now the Taweret submodule update was also added to this PR, so this one counts for both.

**Comment by asemposki** [comment]
I added John to the reviewer list since he's a Taweret coder :)

**Comment by jcyannotty** [comment]
Update on installation:

Remove the following from requirements.txt: math, mpl_toolkits, time, warnings. These come with your python installation so for example, you can't do `pip install math`. Once you remove these four packages from the requirements.txt file, `pip install -r requirements.txt` should work (let me know if it doesn't). 

Once the packages are installed, pytest works great and all tests pass!

Also, Taweret submodule looks good to me.

**Comment by asemposki** [comment]
OK great---I removed the math one, need to remove the others. Will do now.

**Comment by asemposki** [comment]
OK final commit for SAMBA should be linked now in this PR.

**Review by jcyannotty — APPROVED** [review]
SAMBA works for me after the fix to the requirements.txt file.

Taweret submodule is up to date with most recent commits.

**Comment by wildsm** [comment]
Please add 
`-  [Taweretbandsdk.md](https://github.com/bandframework/Taweret/blob/main/Taweretbandsdk.md)`
to the end of resources/sdkpolicies/README.md

**Comment by wildsm** [comment]
I would update setup.py to reflect the updated requirements and would change the two SAMBA to samba for case-sensitive systems (or go to a single way of installing and specify what it is).

**Comment by asemposki** [comment]
All proposed changes from @wildsm have been included in the two commits above.

**Comment by wildsm** [comment]
I am still having problems building SAMBA but it may be a local issue.

Maybe another reviewer (@ozgesurer? @mosesyhc?) can update see whether they are able to do a clean install, build, and run?

**Comment by mosesyhc** [comment]
I followed the README testing instructions and have the following observations:

- `jupyter`, `pytest`, and/or `pytest-cov` dependencies are assumed.  It might be good to add a line before Testing to specify these dependencies.
- `pytest` under Tests/ directory succeeded.
- Jupyter notebooks under Tutorials fail at different spots.  I have attempted to run all blocks and exported the HTML with errors, [attached here](https://www.dropbox.com/scl/fo/1zyhq9sohug6595kcwxe5/h?rlkey=8mobzkdha0jwsvz8fzszm317s&dl=0)

**Comment by ozgesurer** [comment]
Happy to review @asemposki. Perhaps after Moses' checks are incorporated let me know and I can rerun with the updated version? or do you just want me to try the current version?

**Comment by asemposki** [comment]
Thanks @mosesyhc for the careful review. I had forgotten to update the Tutorials, so now all have been updated and run locally for me, so if @ozgesurer wants to check them, that would be appreciated. I know the pytests have worked for everyone. I also updated the README.md for the Tests folder to reflect that people will need pytest and Jupyter notebook to run the tests.

**Comment by asemposki** [comment]
@ozgesurer everything should now be up to date :)

**Review by mosesyhc — APPROVED** [review]
@asemposki: All tutorials are running successfully now. 🎉 

Two minor changes before merging:
- Update the submodule pointer before merge
- Merge from bandframework:develop to get the updated CI, the github actions should succeed now.

**Comment by asemposki** [comment]
Reopening this PR because I had to update my branch of bandframework:develop before being able to merge this.

**Comment by ozgesurer** [comment]
@asemposki So, I am not checking it then. I am sure it runs smoothly :) Sorry, I wasn't able to test immediately. But, let me know if it is needed. @wildsm you can assign me if there is something to do.

**Comment by asemposki** [comment]
I have attempted to find out what is wrong with the checks; I have updated the asemposki/bandframework:develop repo, so there are no new commits to fetch from here. I have pushed the submodule pointers, and the checks still claim that either 'Taweretbandsdk' itself is misspelled, or that the link is broken, yet when I click on it it works. I cannot find any other mistakes in our files. @mosesyhc if you know what's going on with this could you point me in the right direction?

**Comment by asemposki** [comment]
Or @ozgesurer if you want to look at the Actions that would be great. I am not sure what's stopping this from passing checks.

**Comment by wildsm** [comment]
@asemposki - can you create a new branch (from develop) on bandframework? Then you could pull request [asemposki/bandframework](https://github.com/asemposki/bandframework) to that branch (and you could merge yourself since it is not develop or main). The branch would then pass the tests. Right now I think others cannot contribute to [asemposki/bandframework](https://github.com/asemposki/bandframework)  since it is a fork on the asemposki organization, which has different rules.

An alternative would be to update [asemposki/bandframework](https://github.com/asemposki/bandframework) based on the current develop on bandframework.

**Comment by mosesyhc** [comment]
@asemposki : As @wildsm has mentioned, with only one addition.  I believe spellcheck will still fail, we will need to add `Taweretbandsdk` into .github/config/.wordlist.txt so that spellcheck recognizes the word.

**Comment by mosesyhc** [comment]
Looking slightly closer, it seems like both checks are complaining about `Taweretbandsdk`. My first try would be to add that to `.github/config/.wordlist.txt`. I tried to PR into this branch and I have no privilege to do so.

**Comment by asemposki** [comment]
In the test PR from @wildsm, all checks are passing, so let's just use that PR instead of this one (simpler solution).

**Pull request merged**
